<?xml version="1.0" encoding="UTF-8"?><record_update>
    <sys_documentation element="database_name" label="Data Source Name" language="en" table="x_ibmrt_gdpva_test_exception">
        <sys_documentation action="INSERT_OR_UPDATE">
            <element>database_name</element>
            <help/>
            <hint/>
            <label>Data Source Name</label>
            <language>en</language>
            <name>x_ibmrt_gdpva_test_exception</name>
            <plural>Data Source Names</plural>
            <sys_class_name>sys_documentation</sys_class_name>
            <sys_created_by>admin</sys_created_by>
            <sys_created_on>2022-04-27 16:51:55</sys_created_on>
            <sys_id>9a52306e1b74e1106c968559cc4bcbbc</sys_id>
            <sys_mod_count>1</sys_mod_count>
            <sys_name>Data Source Name</sys_name>
            <sys_package display_value="IBM Guardium Data Protection" source="x_ibmrt_gdpva">400d30552fa0111049572f2ef699b65a</sys_package>
            <sys_policy/>
            <sys_scope display_value="IBM Guardium Data Protection">400d30552fa0111049572f2ef699b65a</sys_scope>
            <sys_update_name>sys_documentation_x_ibmrt_gdpva_test_exception_database_name_en</sys_update_name>
            <sys_updated_by>admin</sys_updated_by>
            <sys_updated_on>2022-04-29 12:25:18</sys_updated_on>
            <url/>
            <url_target/>
        </sys_documentation>
    </sys_documentation>
</record_update>
